version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: communitymanagement
      MYSQL_ROOT_PASSWORD: Naruto269815421!
      TZ: UTC
    volumes:
      - mysql-local:/var/lib/mysql
    ports:
      - 3307:3307


# permanent storage of data.
volumes:
  mysql-local: